import type {Complex, Exercise, Language, LocalizedText} from './types';

const text = (ru: string, ro: string, en: string): LocalizedText => ({ru, ro, en});

export const EXERCISES: Exercise[] = [
  {id: 'up-down', name: text('Вверх-Вниз', 'Sus-Jos', 'Up-Down'), instruction: text('Начинаем. Медленно двигайте глазами вверх, затем вниз.', 'Să începem. Mișcați încet ochii în sus, apoi în jos.', 'Let’s begin. Slowly move your eyes up, then down.'), category: 'movement', durationSeconds: 30, animationType: 'up-down'},
  {id: 'left-right', name: text('Вправо-Влево', 'Stânga-Dreapta', 'Left-Right'), instruction: text('Медленно двигайте глазами вправо, затем влево.', 'Mișcați încet ochii la dreapta, apoi la stânga.', 'Slowly move your eyes to the right, then to the left.'), category: 'movement', durationSeconds: 30, animationType: 'left-right'},
  {id: 'diagonal', name: text('Диагональ', 'Diagonală', 'Diagonal'), instruction: text('Посмотрите в верхний правый угол, затем в нижний левый. Повторите для другой диагонали.', 'Priviți în colțul din dreapta sus, apoi în cel din stânga jos. Repetați pentru cealaltă diagonală.', 'Look at the top-right corner, then the bottom-left. Repeat for the other diagonal.'), category: 'movement', durationSeconds: 30, animationType: 'diagonal-x'},
  {id: 'circle', name: text('Круг', 'Cerc', 'Circle'), instruction: text('Медленно вращайте глазами по часовой стрелке, затем против.', 'Rotiți încet ochii în sensul acelor de ceasornic, apoi invers.', 'Slowly rotate your eyes clockwise, then counterclockwise.'), category: 'movement', durationSeconds: 30, animationType: 'circle'},
  {id: 'blink', name: text('Частое моргание', 'Clipit des', 'Frequent Blinking'), instruction: text('Быстро моргайте в течение 10 секунд.', 'Clipiți rapid timp de 10 secunde.', 'Blink quickly for 10 seconds.'), category: 'relaxation', durationSeconds: 10, animationType: 'blink'},
  {id: 'focus', name: text('Фокусировка', 'Focalizare', 'Focus'), instruction: text('Сфокусируйтесь на пальце перед носом, затем на дальнем объекте.', 'Concentrați-vă pe degetul din fața nasului, apoi pe un obiect îndepărtat.', 'Focus on your finger in front of your nose, then on a distant object.'), category: 'accommodation', durationSeconds: 30, animationType: 'focus'},
  {id: 'square', name: text('Схема «Квадрат»', 'Schema „Pătrat”', 'Square Pattern'), instruction: text('Проведите глазами по контуру воображаемого квадрата. Четыре точки фиксации.', 'Urmăriți cu ochii conturul unui pătrat imaginar. Patru puncte de fixare.', 'Trace the outline of an imaginary square with your eyes. Use four fixation points.'), category: 'coordination', durationSeconds: 30, animationType: 'square'},
  {id: 'snake', name: text('Схема «Змейка»', 'Schema „Șarpe”', 'Snake Pattern'), instruction: text('Двигайте глазами по горизонтальной волнистой траектории, затем обратно.', 'Mișcați ochii de-a lungul unei traiectorii ondulate orizontale, apoi înapoi.', 'Move your eyes along a horizontal wavy path, then back.'), category: 'coordination', durationSeconds: 30, animationType: 'snake'},
  {id: 'palming', name: text('Пальминг', 'Palming', 'Palming'), instruction: text('Разотрите ладони до тепла и приложите к закрытым глазам.', 'Frecați palmele până se încălzesc, apoi așezați-le peste ochii închiși.', 'Rub your palms until warm, then place them over your closed eyes.'), category: 'relaxation', durationSeconds: 30, animationType: 'palming'},
  {id: 'focus-approach', name: text('Фокусировка с приближением', 'Focalizare cu apropiere', 'Focus Approach'), instruction: text('Вытяните палец и медленно приближайте его к носу, не теряя фокус.', 'Întindeți degetul și apropiați-l încet de nas, menținând focalizarea.', 'Extend your finger and slowly bring it toward your nose while maintaining focus.'), category: 'accommodation', durationSeconds: 30, animationType: 'focus-zoom'},
  {id: 'butterfly', name: text('Бабочка', 'Fluturele', 'Butterfly'), instruction: text('Легко и очень быстро моргайте, словно бабочка машет крыльями.', 'Clipiți ușor și foarte rapid, ca un fluture care dă din aripi.', 'Blink lightly and quickly, like a butterfly flapping its wings.'), category: 'relaxation', durationSeconds: 20, animationType: 'butterfly'},
  {id: 'infinity', name: text('Бесконечность', 'Infinit', 'Infinity'), instruction: text('Плавно обводите глазами знак бесконечности в обе стороны.', 'Desenați lin simbolul infinitului cu ochii în ambele direcții.', 'Smoothly trace the infinity symbol with your eyes in both directions.'), category: 'coordination', durationSeconds: 30, animationType: 'infinity'},
  {id: 'nose-writing', name: text('Письмо носом', 'Scrisul cu nasul', 'Nose Writing'), instruction: text('Закройте глаза. Представьте, что нос — карандаш, и напишите им в воздухе алфавит.', 'Închideți ochii. Imaginați-vă că nasul este un creion și scrieți alfabetul în aer.', 'Close your eyes. Imagine your nose is a pencil and write the alphabet in the air.'), category: 'relaxation', durationSeconds: 30, animationType: 'nose-writing'},
  {id: 'malyshev-switches', name: text('Горизонтальные и вертикальные переключения', 'Comutări orizontale și verticale', 'Horizontal and Vertical Switches'), instruction: text('Поднимите большие пальцы на ширине плеч. Переводите взгляд справа налево 30 раз, затем вверх-вниз 30 раз.', 'Ridicați degetele mari la lățimea umerilor. Mutați privirea dreapta-stânga de 30 de ori, apoi sus-jos de 30 de ori.', 'Raise both thumbs shoulder-width apart. Switch your gaze right-to-left 30 times, then up-and-down 30 times.'), category: 'method', durationSeconds: 70, animationType: 'malyshev-switches'},
  {id: 'malyshev-convergence', name: text('Раздельное сведение к переносице', 'Convergență separată spre nas', 'Separate Nose Convergence'), instruction: text('Прикройте один глаз. Медленно приближайте палец противоположной руки к переносице 10 раз, затем поменяйте сторону.', 'Acoperiți un ochi. Apropiați încet degetul mâinii opuse de nas de 10 ori, apoi schimbați partea.', 'Cover one eye. Slowly bring the opposite thumb toward the bridge of your nose 10 times, then switch sides.'), category: 'method', durationSeconds: 70, animationType: 'malyshev-convergence'},
  {id: 'malyshev-circle', name: text('Слежение по круговой траектории', 'Urmărire circulară', 'Circular Tracking'), instruction: text('Следите за большим пальцем по кругу: 10 раз по часовой стрелке и 10 против, затем поменяйте руку.', 'Urmăriți degetul mare în cerc: de 10 ori în sensul acelor de ceasornic și de 10 ori invers, apoi schimbați mâna.', 'Follow your thumb in a circle: 10 times clockwise and 10 counterclockwise, then switch hands.'), category: 'method', durationSeconds: 80, animationType: 'malyshev-circle'},
];

export const BASE_EXERCISE_IDS = ['up-down', 'left-right', 'diagonal', 'circle', 'blink', 'focus'];
export const PREMIUM_EXERCISE_IDS = ['square', 'snake', 'palming', 'focus-approach', 'butterfly', 'infinity', 'nose-writing'];

export const COMPLEXES: Complex[] = [
  {id: 'quick-start', name: text('Быстрый старт', 'Start rapid', 'Quick Start'), description: text('Короткая разминка для начала дня.', 'O încălzire scurtă pentru începutul zilei.', 'A short warm-up to begin the day.'), advertisedMinutes: 3, selection: {type: 'fixed', exerciseIds: BASE_EXERCISE_IDS}},
  {id: 'work-break', name: text('Рабочий перерыв', 'Pauză de lucru', 'Work Break'), description: text('Случайный комплекс после работы за экраном.', 'Un set aleatoriu după lucrul la ecran.', 'A randomized routine after screen work.'), advertisedMinutes: 5, selection: {type: 'random', pool: 'all', count: 10}},
  {id: 'full-recovery', name: text('Полное восстановление', 'Recuperare completă', 'Full Recovery'), description: text('Расширенный набор для глубокого расслабления.', 'Un set extins pentru relaxare profundă.', 'An extended routine for deep relaxation.'), advertisedMinutes: 8, selection: {type: 'random', pool: 'premium', count: 7}},
  {id: 'stress-relief', name: text('Снятие напряжения', 'Eliberare de stres', 'Stress Relief'), description: text('Смешанный случайный комплекс для уставших глаз.', 'Un set mixt aleatoriu pentru ochii obosiți.', 'A mixed randomized routine for tired eyes.'), advertisedMinutes: 10, selection: {type: 'random', pool: 'mixed', count: 10}},
  {id: 'focus-marathon', name: text('Фокус-марафон', 'Maraton de concentrare', 'Focus Marathon'), description: text('Упражнения на фокусировку и мягкое расслабление.', 'Exerciții pentru focalizare și relaxare blândă.', 'Exercises for focusing and gentle relaxation.'), advertisedMinutes: 7, selection: {type: 'fixed', exerciseIds: ['focus-approach', 'nose-writing', 'infinity', 'palming']}},
  {id: 'malyshev-method', name: text('Метод Малышева', 'Metoda Malyshev', 'Malyshev Method'), description: text('Три последовательных упражнения по оригинальной схеме.', 'Trei exerciții consecutive după schema originală.', 'Three consecutive exercises following the original routine.'), advertisedMinutes: 4, selection: {type: 'fixed', exerciseIds: ['malyshev-switches', 'malyshev-convergence', 'malyshev-circle']}},
];

export const EXERCISE_BY_ID = new Map(EXERCISES.map((exercise) => [exercise.id, exercise]));
export const COMPLEX_BY_ID = new Map(COMPLEXES.map((complex) => [complex.id, complex]));

export function localize(value: LocalizedText, language: Language): string {
  return value[language];
}
