import { Category, Exercise, Complex } from './types';

export const EXERCISES: Exercise[] = [
  // Basic
  {
    id: 'up-down',
    name: 'Вверх-Вниз',
    nameRo: 'Sus-Jos',
    instruction: 'Медленно двигайте глазами вверх, затем вниз. Повторяйте.',
    instructionRo: 'Mutați încet ochii în sus, apoi în jos. Repetați.',
    category: Category.BASIC,
    duration: 30,
    isPro: false,
    animationType: 'up-down',
  },
  {
    id: 'left-right',
    name: 'Вправо-Влево',
    nameRo: 'Dreapta-Stânga',
    instruction: 'Медленно двигайте глазами вправо, затем влево. Повторяйте.',
    instructionRo: 'Mutați încet ochii la dreapta, apoi la stânga. Repetați.',
    category: Category.BASIC,
    duration: 30,
    isPro: false,
    animationType: 'left-right',
  },
  {
    id: 'diagonal-x',
    name: 'Диагональ (X)',
    nameRo: 'Diagonală (X)',
    instruction: 'Посмотрите в верхний правый угол, затем в нижний левый. Повторите для другой диагонали.',
    instructionRo: 'Priviți în colțul din dreapta sus, apoi în cel din stânga jos. Repetați pentru cealaltă diagonală.',
    category: Category.BASIC,
    duration: 30,
    isPro: false,
    animationType: 'diagonal-x',
  },
  {
    id: 'circle',
    name: 'Круг',
    nameRo: 'Cerc',
    instruction: 'Медленно совершайте глазами полный круг по часовой стрелке, затем против.',
    instructionRo: 'Rotitți încet ochii într-un cerc complet în sensul acelor de ceasornic, apoi invers.',
    category: Category.BASIC,
    duration: 30,
    isPro: false,
    animationType: 'circle',
  },
  {
    id: 'blink',
    name: 'Частое моргание',
    nameRo: 'Clipit des',
    instruction: 'Быстро поморгайте в течение 10 секунд, затем закройте глаза.',
    instructionRo: 'Clipiți rapid timp de 10 secunde, apoi închideți ochii.',
    category: Category.RELAX,
    duration: 30,
    isPro: false,
    animationType: 'blink',
  },
  {
    id: 'focus',
    name: 'Фокусировка (Близко-Далеко)',
    nameRo: 'Focalizare (Aproape-Departe)',
    instruction: 'Сфокусируйтесь на пальце перед носом, затем на дальнем объекте за окном.',
    instructionRo: 'Focalizați-vă pe degetul din fața nasului, apoi pe un obiect îndepărtat de afară.',
    category: Category.ACCOMMODATION,
    duration: 30,
    isPro: false,
    animationType: 'focus',
  },
  // Premium
  {
    id: 'square',
    name: 'Схема «Квадрат»',
    nameRo: 'Schema „Pătrat”',
    instruction: 'Проведите глазами по контуру воображаемого квадрата. Четыре точки фиксации.',
    instructionRo: 'Urmați cu ochii conturul unui pătrat imaginar. Patru puncte de fixare.',
    category: Category.COORDINATION,
    duration: 30,
    isPro: false,
    animationType: 'square',
  },
  {
    id: 'snake',
    name: 'Схема «Змейка»',
    nameRo: 'Schema „Șarpe”',
    instruction: 'Двигайте глазами по горизонтальной волнистой траектории, затем обратно.',
    instructionRo: 'Mutați ochii de-a lungul unei traiectorii orizontale ondulate, apoi înapoi.',
    category: Category.COORDINATION,
    duration: 30,
    isPro: false,
    animationType: 'snake',
  },
  {
    id: 'palming',
    name: 'Пальминг (расширенный)',
    nameRo: 'Palming (extins)',
    instruction: 'Разотрите ладони, приложите к закрытым глазам. Глубокое расслабление.',
    instructionRo: 'Frecați palmele și puneți-le peste ochii închiși. Relaxare profundă.',
    category: Category.RELAX,
    duration: 30,
    isPro: false,
    animationType: 'palming',
  },
  {
    id: 'focus-zoom',
    name: 'Фокусировка с приближением',
    nameRo: 'Focalizare cu apropiere',
    instruction: 'Вытяните палец, медленно приближайте его к носу, не теряя фокус.',
    instructionRo: 'Întindeți degetul, apropiați-l încet de nas, fără a pierde focalizarea.',
    category: Category.ADVANCED_ACCOMMODATION,
    duration: 30,
    isPro: false,
    animationType: 'focus-zoom',
  },
  {
    id: 'cross',
    name: 'Глаза в разные стороны',
    nameRo: 'Ochii în direcții diferite',
    instruction: 'Попробуйте свести глаза к переносице, затем медленно разведите их в стороны.',
    instructionRo: 'Încercați să aduceți ochii la baza nasului, apoi depărtați-i încet în lateral.',
    category: Category.CONVERGENCE,
    duration: 30,
    isPro: false,
    animationType: 'cross',
  },
  {
    id: 'blink-squeeze',
    name: 'Моргание со жмурением',
    nameRo: 'Clipit cu strângere',
    instruction: '10 секунд моргайте, затем крепко зажмурьтесь. Повторить 3 раза.',
    instructionRo: 'Clipiți timp de 10 secunde, apoi strângeți tare ochii. Repetați de 3 ori.',
    category: Category.TONUS,
    duration: 30,
    isPro: false,
    animationType: 'blink-squeeze',
  },
];

export const COMPLEXES: Complex[] = [
  {
    id: 'quick-start',
    name: 'Быстрый старт',
    nameRo: 'Start rapid',
    description: 'Идеально для начала дня или короткого перерыва.',
    descriptionRo: 'Ideal pentru începutul zilei sau o scurtă pauză.',
    exercises: ['up-down', 'left-right', 'diagonal-x', 'circle', 'blink', 'focus'],
    isPro: false,
    durationTotal: 4,
  },
  {
    id: 'work-break',
    name: 'Рабочий перерыв',
    nameRo: 'Pauză de lucru',
    description: 'Снимает усталость после долгой работы за компьютером.',
    descriptionRo: 'Ameliorează oboseala după o muncă lungă la calculator.',
    exercises: ['up-down', 'left-right', 'diagonal-x', 'circle', 'blink', 'focus', 'up-down', 'left-right', 'circle', 'blink'],
    isPro: false,
    durationTotal: 6,
  },
  {
    id: 'full-recovery',
    name: 'Полное восстановление',
    nameRo: 'Recuperare completă',
    description: 'Глубокая проработка мышц глаз и комплексное расслабление.',
    descriptionRo: 'Lucru profund asupra mușchilor ochilor și relaxare complexă.',
    exercises: ['up-down', 'left-right', 'diagonal-x', 'circle', 'square', 'snake', 'palming', 'focus-zoom', 'cross', 'blink-squeeze'],
    isPro: false,
    durationTotal: 8,
  },
  {
    id: 'tension-relief',
    name: 'Снятие напряжения',
    nameRo: 'Relaxare tensiune',
    description: 'Максимальное расслабление и тонус для глаз.',
    descriptionRo: 'Relaxare maximă și tonus pentru ochi.',
    exercises: ['circle', 'blink', 'palming', 'blink-squeeze', 'snake', 'focus', 'focus-zoom', 'square', 'cross', 'palming'],
    isPro: false,
    durationTotal: 10,
  },
];
