import { Category, Exercise, Complex } from './types';

export const EXERCISES: Exercise[] = [
  // Basic
  {
    id: 'up-down',
    name: 'Вверх-Вниз',
    instruction: 'Медленно двигайте глазами вверх, затем вниз. Повторяйте.',
    category: Category.BASIC,
    duration: 30,
    isPro: false,
    animationType: 'up-down',
  },
  {
    id: 'left-right',
    name: 'Вправо-Влево',
    instruction: 'Медленно двигайте глазами вправо, затем влево. Повторяйте.',
    category: Category.BASIC,
    duration: 30,
    isPro: false,
    animationType: 'left-right',
  },
  {
    id: 'diagonal-x',
    name: 'Диагональ (X)',
    instruction: 'Посмотрите в верхний правый угол, затем в нижний левый. Повторите для другой диагонали.',
    category: Category.BASIC,
    duration: 30,
    isPro: false,
    animationType: 'diagonal-x',
  },
  {
    id: 'circle',
    name: 'Круг',
    instruction: 'Медленно совершайте глазами полный круг по часовой стрелке, затем против.',
    category: Category.BASIC,
    duration: 30,
    isPro: false,
    animationType: 'circle',
  },
  {
    id: 'blink',
    name: 'Частое моргание',
    instruction: 'Быстро поморгайте в течение 10 секунд, затем закройте глаза.',
    category: Category.RELAX,
    duration: 30,
    isPro: false,
    animationType: 'blink',
  },
  {
    id: 'focus',
    name: 'Фокусировка (Близко-Далеко)',
    instruction: 'Сфокусируйтесь на пальце перед носом, затем на дальнем объекте за окном.',
    category: Category.ACCOMMODATION,
    duration: 30,
    isPro: false,
    animationType: 'focus',
  },
  // Premium
  {
    id: 'square',
    name: 'Схема «Квадрат»',
    instruction: 'Проведите глазами по контуру воображаемого квадрата. Четыре точки фиксации.',
    category: Category.COORDINATION,
    duration: 30,
    isPro: true,
    animationType: 'square',
  },
  {
    id: 'snake',
    name: 'Схема «Змейка»',
    instruction: 'Двигайте глазами по горизонтальной волнистой траектории, затем обратно.',
    category: Category.COORDINATION,
    duration: 30,
    isPro: true,
    animationType: 'snake',
  },
  {
    id: 'palming',
    name: 'Пальминг (расширенный)',
    instruction: 'Разотрите ладони, приложите к закрытым глазам. Глубокое расслабление.',
    category: Category.RELAX,
    duration: 30,
    isPro: true,
    animationType: 'palming',
  },
  {
    id: 'focus-zoom',
    name: 'Фокусировка с приближением',
    instruction: 'Вытяните палец, медленно приближайте его к носу, не теряя фокус.',
    category: Category.ADVANCED_ACCOMMODATION,
    duration: 30,
    isPro: true,
    animationType: 'focus-zoom',
  },
  {
    id: 'cross',
    name: 'Глаза в разные стороны',
    instruction: 'Попробуйте свести глаза к переносице, затем медленно разведите их в стороны.',
    category: Category.CONVERGENCE,
    duration: 30,
    isPro: true,
    animationType: 'cross',
  },
  {
    id: 'blink-squeeze',
    name: 'Моргание со жмурением',
    instruction: '10 секунд моргайте, затем крепко зажмурьтесь. Повторить 3 раза.',
    category: Category.TONUS,
    duration: 30,
    isPro: true,
    animationType: 'blink-squeeze',
  },
];

export const COMPLEXES: Complex[] = [
  {
    id: 'quick-start',
    name: 'Быстрый старт',
    description: 'Идеально для начала дня или короткого перерыва.',
    exercises: ['up-down', 'left-right', 'diagonal-x', 'circle', 'blink', 'focus'],
    isPro: false,
    durationTotal: 4, // roughly
  },
  {
    id: 'work-break',
    name: 'Рабочий перерыв',
    description: 'Снимает усталость после долгой работы за компьютером.',
    exercises: ['up-down', 'left-right', 'diagonal-x', 'circle', 'blink', 'focus', 'up-down', 'left-right', 'circle', 'blink'],
    isPro: false,
    durationTotal: 6,
  },
  {
    id: 'full-recovery',
    name: 'Полное восстановление',
    description: 'Глубокая проработка мышц глаз и комплексное расслабление.',
    exercises: ['up-down', 'left-right', 'diagonal-x', 'circle', 'square', 'snake', 'palming', 'focus-zoom', 'cross', 'blink-squeeze'],
    isPro: true,
    durationTotal: 8,
  },
  {
    id: 'tension-relief',
    name: 'Снятие напряжения',
    description: 'Максимальное расслабление и тонус для глаз.',
    exercises: ['circle', 'blink', 'palming', 'blink-squeeze', 'snake', 'focus', 'focus-zoom', 'square', 'cross', 'palming'],
    isPro: true,
    durationTotal: 10,
  },
];
